#!/bin/bash

# GitHub Webhook Setup Guide for Jenkins
# This script provides instructions and examples for setting up GitHub webhooks

echo "GitHub Webhook Setup for Jenkins"
echo "================================"
echo ""
echo "1. Go to your GitHub repository settings"
echo "2. Navigate to Webhooks section"
echo "3. Click 'Add webhook'"
echo "4. Set the Payload URL to:"
echo "   https://jenkins-react-vite-npm.onrender.com/github-webhook/"
echo ""
echo "5. Set Content type to: application/json"
echo "6. Select events:"
echo "   - Push events"
echo "   - Pull request events"
echo "   - Branch or tag creation"
echo "   - Branch or tag deletion"
echo ""
echo "7. Make sure the webhook is Active"
echo ""
echo "Jenkins Job Configuration:"
echo "========================="
echo "1. Create a new Pipeline job in Jenkins"
echo "2. In 'Pipeline' section, select 'Pipeline script from SCM'"
echo "3. Set SCM to 'Git'"
echo "4. Add your repository URL: https://github.com/meetSabhani02/jenkins-react-vite-npm.git"
echo "5. Set branch to: */main"
echo "6. Script Path: Jenkinsfile"
echo ""
echo "Build Triggers:"
echo "=============="
echo "1. Check 'GitHub hook trigger for GITScm polling'"
echo "2. Check 'Poll SCM' (leave schedule empty)"
echo ""
echo "The pipeline will now trigger on pushes to main branch!"
echo ""
echo "Build Artifacts:"
echo "==============="
echo "After each successful build, you'll find:"
echo "- dist/ folder with compiled assets"
echo "- artifacts/*.zip files with packaged builds"
echo "- Build artifacts downloadable from Jenkins UI"